name: Awesome-CV-CI

on: 
  workflow_dispatch:
    

jobs:
  awesome-cv-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olivierodo/awesome-cv-action@0.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        FILE_NAME: 'Devendra_Sahu-DevOps-9Years.tex'
        LATEST_TAG: 'false' 